import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import SideMenu from "@/components/SideMenu";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className} h-screen`}>
        <div className="grid grid-rows-[80px_1fr]">
        <Header />
        <div className="grid grid-cols-[80px_1fr]">
          <SideMenu />
          <div className="h-screen">{children}</div>
        </div>
        </div>
      </body>
    </html>
  );
}
